# ============================================================================
# INSTALL COMMAND
# ============================================================================
from pathlib import Path

from src.perf.performance import timed_command


def auto_detect_path(candidates: list) -> Path:
    """Try to auto-detect path from candidates"""
    for path_str in candidates:
        path = Path(os.path.expanduser(path_str))
        if path.exists():
            return path
    return None


def prompt_path(message: str, default: str = None) -> str:
    """Prompt user for path with optional default"""
    if default:
        user_input = input(f"{message} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{message}: ").strip()
            if user_input:
                return user_input
            print("  Path required. Please try again.")


@timed_command
def cmd_install(args):
    """Interactive setup - auto-detect paths and create .env"""
    import platform

    print("Terra Invicta Advisory System - Installation")
    print("=" * 60)

    is_windows = platform.system() == 'Windows'
    print(f"Detected OS: {'Windows' if is_windows else 'Linux'}")
    print()

    # Auto-detect game installation
    print("[1/5] Detecting game installation...")
    game_candidates = [
        "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Terra Invicta",
        "~/.steam/steam/steamapps/common/Terra Invicta",
        "~/.local/share/Steam/steamapps/common/Terra Invicta"
    ]
    game_dir = auto_detect_path(game_candidates)

    if game_dir:
        print(f"  Found: {game_dir}")
        confirm = input("  Use this path? [Y/n]: ").strip().lower()
        if confirm in ['n', 'no']:
            game_dir = prompt_path("  Enter game install path")
    else:
        print("  Not found in common locations")
        game_dir = prompt_path("  Enter game install path")

    # Auto-detect saves directory
    print("\n[2/5] Detecting saves directory...")
    saves_candidates = [
        "C:\\Users\\" + os.getenv('USERNAME', 'User') + "\\Documents\\My Games\\TerraInvicta\\Saves",
        "~/.local/share/Pavonis Interactive/Terra Invicta/Saves"
    ]
    saves_dir = auto_detect_path(saves_candidates)

    if saves_dir:
        print(f"  Found: {saves_dir}")
        confirm = input("  Use this path? [Y/n]: ").strip().lower()
        if confirm in ['n', 'no']:
            saves_dir = prompt_path("  Enter saves directory")
    else:
        print("  Not found in common locations")
        saves_dir = prompt_path("  Enter saves directory")

    # Prompt for KoboldCpp (can't auto-detect)
    print("\n[3/5] KoboldCpp configuration...")
    kobold_dir = prompt_path("  KoboldCpp directory")

    print("\n[4/5] Model configuration...")
    print("  Note: Configure base model only (others optional)")
    model_path_base = prompt_path("  Base model path (mistral-7b-q4.gguf)")

    # GPU backend
    print("\n[5/5] GPU backend selection...")
    if is_windows:
        print("  Recommended for Windows + AMD: vulkan")
        gpu_backend = prompt_path("  GPU backend", "vulkan")
    else:
        print("  Recommended for Linux + AMD: clblast (requires ROCm)")
        print("  Alternative: vulkan (works on any GPU)")
        gpu_backend = prompt_path("  GPU backend", "clblast")

    # Write .env file
    print("\n" + "=" * 60)
    print("Writing .env file...")

    project_root = get_project_root()
    env_file = project_root / ".env"
    gitignore_file = project_root / ".gitignore"

    # Ensure .env is in .gitignore
    if gitignore_file.exists():
        with open(gitignore_file) as f:
            gitignore_content = f.read()
        if '.env' not in gitignore_content and '*.env' not in gitignore_content:
            print("\nWARNING: .env not found in .gitignore")
            print("Adding .env to .gitignore to prevent committing secrets...")
            with open(gitignore_file, 'a') as f:
                f.write("\n# Environment configuration (contains secrets)\n.env\n")
    else:
        print("\nWARNING: .gitignore not found")
        print("Creating .gitignore to protect .env file...")
        with open(gitignore_file, 'w') as f:
            f.write("# Environment configuration (contains secrets)\n.env\n")

    with open(env_file, 'w') as f:
        f.write("# Terra Invicta Advisory System - Configuration\n")
        f.write(f"# Generated by: bin/tias.py install\n")
        f.write(f"# Date: {datetime.now().isoformat()}\n")
        f.write("\n")

        f.write("# KoboldCpp\n")
        f.write("KOBOLDCPP_URL=http://localhost:5001\n")
        f.write(f"KOBOLDCPP_DIR={kobold_dir}\n")
        f.write(f"KOBOLDCPP_MODEL_BASE={model_path_base}\n")
        f.write(f"KOBOLDCPP_MODEL_MAX=# Optional: Path to mistral-7b-q6.gguf\n")
        f.write(f"KOBOLDCPP_MODEL_NUCLEAR=# Optional: Path to qwen2.5-14b-q4.gguf\n")
        f.write(f"KOBOLDCPP_MODEL_RIDICULOUS=# Optional: Path to qwen2.5-32b-q4.gguf\n")
        f.write(f"KOBOLDCPP_MODEL_LUDICROUS=# Optional: Path to qwen2.5-72b-q2.gguf\n")
        f.write("KOBOLDCPP_QUALITY=base\n")
        f.write("KOBOLDCPP_PORT=5001\n")
        f.write(f"KOBOLDCPP_GPU_BACKEND={gpu_backend}\n")
        f.write("KOBOLDCPP_GPU_LAYERS=35\n")
        f.write("KOBOLDCPP_CONTEXT_SIZE=16384\n")
        f.write("KOBOLDCPP_THREADS=8\n")
        f.write("\n")

        f.write("# Terra Invicta\n")
        f.write(f"GAME_INSTALL_DIR={game_dir}\n")
        f.write("GAME_VERSION=1.0.29\n")
        f.write(f"GAME_SAVES_DIR={saves_dir}\n")
        f.write("\n")

        f.write("# Paths\n")
        f.write("RESOURCES_DIR=./resources\n")
        f.write("BUILD_DIR=./build\n")
        f.write("GENERATED_DIR=./generated\n")
        f.write("LOGS_DIR=./logs\n")
        f.write("\n")

        f.write("# System\n")
        f.write("LOG_LEVEL=INFO\n")
        f.write("CURRENT_TIER=1\n")

    logging.info(f"Created .env file: {env_file}")
    print(f"\n[OK] Installation complete!")
    print(f"  Configuration saved to: {env_file}")
    print(f"\nNext steps:")
    print(f"  1. python bin/tias.py build")
    print(f"  2. python bin/tias.py parse --date YYYY-M-D")
    print(f"  3. python bin/tias.py run --date YYYY-M-D")
